app/config/urls.py
from django.contrib import admin
from django.urls import path, include

import education

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('education.urls')),
]

app/education/urls.py
from django.urls import path

from education import views

urlpatterns = [
    path('', views.index, name='index'),
    path('schools/', views.school_list, name='school-list'),
    path('schools/<int:pk>/', views.school_detail, name='school-detail'),
    path('students/', views.student_list, name='student-list'),
    path('students/<int:pk>/', views.student_detail, name='student-detail'),
]

app/education/models.py
from django.db import models
from django.utils import timezone


class School(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Student(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField('생성 일시', default=timezone.now)

    def __str__(self):
        return self.name

app/education/views.py
from django.shortcuts import render

from education.models import School, Student


def index(request):
    return render(request, 'education/index.html')

def school_list(request):
    schools = School.objects.all()
    context = {
        'schools':schools,
    }
    return render(request, 'education/school_list.html', context)

def school_detail(request, pk):
    school = School.objects.get(id=pk)
    context = {
        'school':school
    }
    return render(request, 'education/school_detail.html', context)

def student_list(request):
    students = Student.objects.all()
    context = {
        'students':students,
    }
    return render(request, 'education/student_list.html', context)

def student_detail(request, pk):

    student = Student.objects.get(id=pk)
    context = {
        'student': student,
    }
    return render(request, 'education/student_detail.html', context)

app/templates/education/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

app/templates/education/index.html
{% extends 'education/base.html' %}

{% block content %}
<h1>Education - 학교와 학생의 정보를 보여줍니다.</h1>

<h3><a href="{% url 'school-list' %}">학교 리스트 보기</a></h3>
<h3><a href="{% url 'student-list' %}">학생 리스트 보기</a></h3>

{% endblock %}

app/templates/education/school_detail.html
{% extends 'education/base.html' %}
{% block content %}
<h2>School Detail</h2>

<h3>{{ school.name }}</h3>
<p>{{ school.description }}</p>

<p> 현재 학생 수 : {{ school.student_set.count }}</p>
{% for student in school.student_set.all %}
<h4><a href="{% url 'student-detail' student.id %}">{{ student }}</a></h4>
{% endfor %}

<a href="{% url 'index' %}">처음으로 돌아가기</a>
{% endblock %}

app/templates/education/school_list.html
{% extends 'education/base.html' %}
{% block content %}
<h2>School List</h2>

{% for school in schools %}
<a href="{% url 'school-detail' school.id %}">{{ school }}</a>
{% endfor %}

<a href="{% url 'index' %}">처음으로 돌아가기</a>
{% endblock %}

app/templates/education/student_detail.html
{% extends 'education/base.html' %}
{% block content %}
<h2>Student Detail</h2>

<h4>{{ student.name }}</h4>
<p>학교 : <a href="{% url 'school-detail' student.school.id %}">{{ student.school }}</a></p>
<p>생성일자 : {{ student.created_at }}</p>

<a href="{% url 'index' %}">처음으로 돌아가기</a>
{% endblock %}

app/templates/education/student_list.html
{% extends 'education/base.html' %}
{% block content %}
<h2>Student List</h2>

{% for student in students %}
<a href="{% url 'student-detail' student.id %}"><h4>{{ student.name }}</h4></a>
{% endfor %}

<a href="{% url 'index' %}">처음으로 돌아가기</a>
{% endblock %}